---
- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Syncthing GPG key
  get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg
    mode: '0644'

- name: Add Syncthing APT repository
  copy:
    content: |
      deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
    dest: /etc/apt/sources.list.d/syncthing.list

- name: Update APT cache  
  apt:
    update_cache: yes

- name: Install Syncthing
  ansible.builtin.package:
    name: syncthing
    state: present
